version: "3.9"
services:
  db:
    image: postgres:13.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - paper-postgres:/var/lib/paper/postgresql/data

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: pappu687
    ports:
      - 8081:8080

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-paper:/data
    command: minio server --console-address ":9001" /data

  # webapp:
  #   image: paper-test:latest
  #   command: bash -lc ". ./.venv/bin/activate && python app/main.py"
  #   ports:
  #     - "80:80"
volumes:
  paper-postgres:
  minio-paper:
