"""Add declined to user invite

Revision ID: 566de0797ff6
Revises: c76a397a958f
Create Date: 2023-12-08 08:18:20.984664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "566de0797ff6"
down_revision: Union[str, None] = "c76a397a958f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_invite",
        sa.Column("declined", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_invite", "declined")
    # ### end Alembic commands ###
