"""update ad offerings

Revision ID: 4131a09945ca
Revises: 814ffc4cad0d
Create Date: 2023-11-13 08:29:51.459461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4131a09945ca'
down_revision: Union[str, None] = '814ffc4cad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_offering', sa.Column('impact_score', sa.Float(), nullable=False))
    op.add_column('ad_offering', sa.Column('size', sa.String(), nullable=False))
    op.add_column('ad_offering', sa.Column('page_start', sa.Integer(), nullable=False))
    op.add_column('ad_offering', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('ad_offering', sa.Column('color', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad_offering', 'color')
    op.drop_column('ad_offering', 'page_end')
    op.drop_column('ad_offering', 'page_start')
    op.drop_column('ad_offering', 'size')
    op.drop_column('ad_offering', 'impact_score')
    # ### end Alembic commands ###
