"""add ad price

Revision ID: e78db470e705
Revises: 4131a09945ca
Create Date: 2023-11-17 19:28:50.810308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e78db470e705"
down_revision: Union[str, None] = "4131a09945ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ad_offering",
        sa.Column("price", sa.Float(), nullable=False, server_default=sa.text("100")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ad_offering", "price")
    # ### end Alembic commands ###
