"""Add index to ad offering

Revision ID: fdd02c5e4d53
Revises: e78db470e705
Create Date: 2023-11-17 22:01:48.191170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fdd02c5e4d53"
down_revision: Union[str, None] = "e78db470e705"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ad_offering",
        sa.Column("index", sa.Integer(), nullable=False, server_default=sa.text("0")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ad_offering", "index")
    # ### end Alembic commands ###
