"""empty message

Revision ID: 6221b1d6a68a
Revises: a3f646d7b6ce
Create Date: 2024-04-16 16:36:37.203119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6221b1d6a68a"
down_revision: Union[str, None] = "a3f646d7b6ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ad_offering",
        sa.Column("x_dimension", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "ad_offering",
        sa.Column("y_dimension", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ad_offering", "y_dimension")
    op.drop_column("ad_offering", "x_dimension")
    # ### end Alembic commands ###
