"""add publication sections

Revision ID: b7ad5d5dde11
Revises: 6221b1d6a68a
Create Date: 2024-04-27 08:40:04.467071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7ad5d5dde11"
down_revision: Union[str, None] = "6221b1d6a68a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "publication",
        sa.Column(
            "sections", sa.ARRAY(sa.VARCHAR()), nullable=False, server_default="{}"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("publication", "sections")
    # ### end Alembic commands ###
